name: svel poll

on:
  schedule:
    - cron: '0 * * * *' # This runs the check automatically every hour
  workflow_dispatch:     # This allows you to click "Run workflow" manually

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Svel Monitor
        run: |
          curl -X POST "https://svel-ai.svel.workers.dev" \
          -H "Authorization: Bearer 0e24bbb2efd1f94cb31d324c1271ebbee416ceeede2e1d75ebbce911d3f39864"
